# Application
spring.application.name=library-management-system
#server.port=8080
server.port=${PORT:8080}

# Database Configuration
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/rahulshettyacademy
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres
#spring.datasource.username=root
spring.datasource.username=postgres.kmbpamsquralquekljyv
#spring.datasource.password=1234
spring.datasource.password=q94zH2j5J1YlHgs8
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.com.library.management=DEBUG

